name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Modify SVG for Light Color
        run: |
          sed -i 's/#000000/#FFFFFF/g' dist/snake.svg  # Example command to change black to white
          # You can add more sed commands to modify other colors as needed

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
